google-github-actions/run-gemini-cli

.github/workflows/gemini-issue-scheduled-triage.yml
examples/workflows/issue-triage/gemini-issue-scheduled-triage.yml

The scheduled issue triage workflow is designed to use a generated GitHub App token. If the "Generate GitHub App Token" step is skipped, the workflow would fail because the GITHUB_TOKEN environment variable would
be empty.

fix(workflows): use GITHUB_TOKEN as fallback in scheduled triage

---

.github/workflows/gemini-pr-review.yml

Restricts the automatic PR review workflow to run only for pull requests opened by repository owners, members, or collaborators. This is a temporary fix for requiring env vars in forks.

feat: unblock community contributions in PR reviews

---

examples/workflows/gemini-cli/README.md
examples/workflows/issue-triage/README.md
examples/workflows/pr-review/README.md

Documentation:
- Update curl command URLs in issue-triage, gemini-cli, and pr-review example READMEs to include the "examples" directory in the path

docs: fix workflow file path at setup section

---

.github/workflows/gemini-pr-review.yml
examples/workflows/pr-review/gemini-pr-review.yml

Rename 'priority' field to 'severity' in the PR review workflow instructions
Documentation:
- Update .github/workflows/gemini-pr-review.yml to use 'severity' instead of 'priority' in comment syntax
- Update example workflow in examples/workflows/pr-review/gemini-pr-review.yml to replace 'priority' with 'severity'

chore: change priority to severity

---

action.yml

GitHub Actions defaults to passing an empty string for optional inputs that are not explicitly set in a workflow. When the `gemini_api_key` input is unset, it is passed as an empty string to the `GEMINI_API_KEY` environment variable.
The Gemini CLI does not handle an empty `GEMINI_API_KEY` variable gracefully, which can lead to unexpected behavior.
This commit addresses the issue by explicitly checking if the `GEMINI_API_KEY` variable is empty (`-z`). If it is, the variable is unset before invoking the Gemini CLI. This ensures the CLI's default authentication behavior (e.g., using Application Default Credentials) is triggered correctly when no API key is provided, improving the action's robustness and predictability.
>Note: This is a temporary workaround to unblock users. The underlying …

fix(action): Unset empty gemini_api_key environment variable

---

.github/workflows/gemini-cli.yml
examples/workflows/gemini-cli/gemini-cli.yml

Update Gemini CLI workflows to mention the actor when posting acknowledgment comments
Enhancements:
- Add GITHUB_ACTOR environment variable to workflows
- Prefix acknowledgment messages with the @mention of the GitHub actor
This is to confirm who responded when multiple people called within the organization.
This is also useful for checking which users have the authority to perform actions.
I've tested this workflow with issue and pull request comments.

chore: mention user to confirm who run

---

.github/workflows/gemini-pr-review.yml
examples/workflows/pr-review/gemini-pr-review.yml

Fix PR workflow to be triggered when users comments `@gemini /review` in a PR
Fixes #109

bug(#109): Support triggering PR review with issue comment

---

.github/workflows/gemini-issue-automated-triage.yml
examples/workflows/issue-triage/gemini-issue-automated-triage.yml

This will help make sure it can access the issue title and body.
Example run needing `echo`: https://github.com/google-github-actions/run-gemini-cli/actions/runs/16816912109/job/47635803167
Note that scheduled triage has `echo` tool already.
cc @leehagoodjames

Add `echo` to core tools for automated issue triage

---

.github/workflows/gemini-pr-review.yml
examples/workflows/pr-review/gemini-pr-review.yml

This change modifies the prompt to constrain the agent on how the review must be submitted to GitHub. This aims to improve what is seen in #134 where  "more than 50% of the time PR review fails due to tool problems posting the review."
Since this is occurring intermittently - this is a probabilistic issue, not a permissions issue, which is why the prompt is being changed.
Primary changes: 
1. Sometimes the agent made tool calls for a fake repo `owner` to make tool calls. The change instructs the agent to list the repository owner. 
1. Surprisingly, even when the agent hallucinated a fake repo `owner` and made tool calls with this, our logs show that these calls were successful (so the agent thought things were working), which is why workflow errors did not surface. I have filed a …

bug(/review): Fix agent not posting feedback in GitHub

---

examples/workflows/CONFIGURATION.md

This is to make sure users know how to allowlist tools and to configure MCP servers.
Related: https://github.com/google-github-actions/run-gemini-cli/issues/145
Preview: https://github.com/google-github-actions/run-gemini-cli/blob/docs/core-tools/examples/workflows/CONFIGURATION.md

Highlight core tools and mcp servers in configuration docs

---

.github/workflows/gemini-cli.yml
.github/workflows/gemini-pr-review.yml
examples/workflows/gemini-cli/gemini-cli.yml
examples/workflows/pr-review/gemini-pr-review.yml

The workflows for https://github.com/google-github-actions/run-gemini-cli enable restrictions on who can invoke them, to prevent abuse scenarios by untrusted users. 
A better solution would enable reliably checking repository membership with `github.event.issue.author_association`, but this is not possible since `github.event.issue.author_association` can return `CONTRIBUTOR` even when the author is also a `MEMBER`. Given this, https://github.com/actions/github-script/issues/643 has been filed with GitHub to allow actions to more easily check for membership. 
This mitigation simplifies the experience for private repos
Fixes #163

feat(workflows): reduce restrictions for invoking workflows for private repos

---

.github/workflows/gemini-cli.yml
.github/workflows/gemini-issue-automated-triage.yml
.github/workflows/gemini-issue-scheduled-triage.yml
.github/workflows/gemini-pr-review.yml
examples/workflows/gemini-cli/gemini-cli.yml
examples/workflows/issue-triage/gemini-issue-automated-triage.yml
examples/workflows/issue-triage/gemini-issue-scheduled-triage.yml
examples/workflows/pr-review/gemini-pr-review.yml

This is a follow-up to #178 which sets the Gemini CLI debug settings.

chore(logging): only enable Gemini debug when DEBUG is set

---

.github/workflows/gemini-issue-automated-triage.yml
.github/workflows/gemini-issue-scheduled-triage.yml
examples/workflows/issue-triage/gemini-issue-automated-triage.yml
examples/workflows/issue-triage/gemini-issue-scheduled-triage.yml

This commit improves the gemini issue triage workflow by:
- Passing the available labels as an environment variable to the Gemini CLI.
- Using the output of the Gemini CLI to apply labels to the issue.
- Adding a step to get all repository labels and pass them to the gemini-cli.
- Updating the prompt to classify the issue and output the labels in JSON format.
- Adding a step to apply the labels to the issue using the github-script.

feat: improve gemini issue triage workflow

---

action.yml

This introduces a new output that holds only the error logs. Previously, the single error stream was being clobbered by both stderr and stdout writing to the same file. Also, you probably want the output values to be different.

fix(output): separate the stdout and stderr logs

---

README.md
examples/workflows/gemini-cli/README.md
examples/workflows/issue-triage/README.md
examples/workflows/pr-review/README.md

- Add .gitignore step to all setup instructions
- Include `.gemini/` and `gha-creds-*.json` entries
Note: Will update /setup-github command to handle gitignore automatically
https://github.com/google-github-actions/run-gemini-cli/issues/196

docs: add gitignore recommendations across all workflows

---

action.yml

It's possible to trick the LLM into printing sensitive information from the environment like access keys or credentials. While GitHub Actions secret masking + shell_command restrictions provide some protections, the best protection is to suppress Gemini CLI output in the logs. The output is still accessible via the `summary` and `error` fields on the GitHub Action, in case later steps do want to print or inspect the output.

bug(output): do not print output by default

---

action.yml

This feels like a reasonable compromise between having no output at all.
- Closes #203 (thanks @iclectic, your commit is in this PR)
- Fixes #189

Stream live output if (and only if) debug mode is enabled

---

README.md
examples/workflows/gemini-assistant/README.md
examples/workflows/gemini-assistant/gemini-invoke.yml

This commit renames the `gemini-cli` workflow to `gemini-invoke` to better reflect its purpose as a general-purpose invocation workflow.
The following changes are included:
- The `examples/workflows/gemini-cli` directory has been moved to `examples/workflows/gemini-invoke`.
- The `README.md` file has been updated to point to the new workflow documentation.
- The `gemini-cli.yml` workflow file has been renamed to `gemini-invoke.yml`.

feat: rename gemini-cli to gemini-invoke

---

examples/workflows/gemini-assistant/gemini-invoke.yml
examples/workflows/issue-triage/gemini-scheduled-triage.yml
examples/workflows/issue-triage/gemini-triage.yml
examples/workflows/pr-review/gemini-review.yml

This pins the version of the run-gemini-cli action to v0 instead of main in the example workflows.
This is a best practice to ensure that users are using a stable version of the action and to avoid unexpected changes in their workflows.
Note that dogfooding uses main instead of v0 to ensure we're testing latest changes before cutting a release.

feat: pin example workflows to v0

---

.github/workflows/gemini-dispatch.yml
.github/workflows/gemini-issue-fixer.yml

Add workflow for `@gemini-cli /fix` to fix a GitHub Issue
This workflow seeks to take similar approaches to other workflows, such as `gemini-cli.yml` or `gemini-pr-review.yml`, but differs primarily in its prompt. The differences aim to enhance the reliability/performance of the workflow by consistently adopting XML tags, removing newline characters that are used solely for breaking up long lines in IDEs, and placing a greater emphasis on providing examples that use least-to-most prompting.
GitHub actions are difficult to test before they are in `main`, as the workflow does not exist at https://github.com/google-github-actions/run-gemini-cli/actions to invoke. Therefore, this change only adds the workflow internally for evaluation/iteration to enable testing, and when it is provably …

feat: support /fix slash command and workflow

---

examples/workflows/pr-review/README.md

- Add comprehensive section on extending PR review workflow to support forks
- Document simple fork support approach using contributor's own Google auth
- Explain GitHub Actions security model for fork-based PRs
- Provide implementation approaches from simple to advanced
- Include security best practices and resources for pull_request_target
- Reference centralized authentication documentation
- Reorganize content with clear implementation approaches
Fixes https://github.com/google-github-actions/run-gemini-cli/issues/191

docs: add fork support documentation for PR review workflow

---

action.yml

Previously, empty API keys caused errors so we handled this by unsetting the empty keys.
As of GenAI SDK version 1.16, this is handled correctly.
This change removes the temporary unsetting of the key.
Related: https://github.com/google-gemini/gemini-cli/pull/7377 
Fixes #248

feat: clean up temp fix for empty API key

---

action.yml
scripts/validate-inputs.sh

Adds a validation step to the action to ensure that authentication inputs are configured correctly. This prevents common misconfigurations and improves security.
The validation is performed by a new script, `scripts/validate-inputs.sh`, which is called as the first step in the action.
Key changes:
- A new `validate-inputs.sh` script is added to check authentication configuration.
- The `action.yml` is updated to call this script.
- Follows principle of least privilege by using boolean flags to indicate whether inputs are set.
- The validation enforces that exactly one authentication method is used, providing clear error messages to the user if the configuration is invalid. This makes the action more robust, secure, and easier to debug.
Fixes …

feat: add auth input validation

---

action.yml

Corrects the quoting of GitHub Actions expressions in `action.yml`. The expression parser was failing when an expression contained single quotes while also being wrapped in single quotes.
This change switches to using double quotes to wrap expressions that contain single quotes, which resolves the parsing error and ensures the workflow functions correctly.

fix(action): correct quoting in workflow expressions

---

scripts/validate-inputs.sh

Introduce error() helper to:
- write to stderr for log visibility
- emit a titled ::error:: annotation for Checks
- append to GITHUB_STEP_SUMMARY for run summary
Replace ad-hoc echo+exit paths with error() across all validation branches.

fix(validate-inputs): surface errors in logs, annotation, and step summary

---

scripts/validate-inputs.sh

Emit ::warning annotations, log to stderr, and append to step summary without failing the step. Replace error exits with warnings across all validation branches.
We can move this to errors in future releases, but don't want to break downstream users once we cut a release.

feat(validate-inputs): downgrade validation failures to warnings

---

action.yml

The input validation script was failing silently and incorrectly when exactly one authentication method was provided. This was due to the interaction between 'set -e' and the exit code of Bash arithmetic evaluation.
The post-increment expression 'auth_methods++' evaluates to 0 when auth_methods is 0. In Bash, an arithmetic expression that evaluates to 0 returns an exit code of 1. With 'set -e' enabled, this non-zero exit code caused the script to exit as if an error had occurred.
This commit changes the post-increment to a pre-increment '++auth_methods'. This ensures the expression always evaluates to a non-zero value (1, 2, or 3), resulting in a 0 exit code and preventing the script from failing.
Additionally, the '-x' flag has been added to the 'set' command to enable xtrace, which will …

fix(action): correct input validation script behavior

---

.github/workflows/gemini-invoke.yml
.github/workflows/gemini-issue-fixer.yml
.github/workflows/gemini-review.yml
.github/workflows/gemini-scheduled-triage.yml
.github/workflows/gemini-triage.yml
examples/workflows/gemini-assistant/gemini-invoke.yml
examples/workflows/issue-triage/gemini-scheduled-triage.yml
examples/workflows/issue-triage/gemini-triage.yml
examples/workflows/pr-review/gemini-review.yml

Adds a security warning to all Gemini CLI workflow prompts, instructing the model to avoid using command substitution features like `$(...)`, `<(...)`, or `>(...)` in shell commands.
This is a preventative measure to avoid errors where the Gemini CLI rejects commands that use command substitution for security reasons. This change makes the security constraints of the tool explicit to the model.

feat: add command substitution security warning

---

.github/workflows/gemini-triage.yml

The `gemini-triage.yml` workflow had a duplicate step number, which caused confusion when reading the workflow. This commit corrects the numbering to be sequential.

fix(triage): correct duplicate step numbering in workflow

---

.github/workflows/gemini-review.yml
.github/workflows/gemini-scheduled-triage.yml
examples/workflows/issue-triage/gemini-scheduled-triage.yml
examples/workflows/issue-triage/gemini-triage.yml
examples/workflows/pr-review/gemini-review.yml

This pull request introduces formatting improvements to the GitHub workflow files for better readability and corrects a numbering error in an example prompt.
To maintain code quality and ensure examples are accurate and easy to read.
- Improved indentation for `run_shell_command` lists in `gemini-review.yml` and `gemini-scheduled-triage.yml`, and their corresponding examples.
- Corrected the step numbering in the prompt within the `examples/workflows/issue-triage/gemini-triage.yml` file - #331.

chore(workflows): Apply formatting and fix example prompt

---

.github/workflows/gemini-invoke.yml
.github/workflows/gemini-issue-fixer.yml
.github/workflows/gemini-review.yml
.github/workflows/gemini-scheduled-triage.yml
.github/workflows/gemini-triage.yml
examples/workflows/gemini-assistant/gemini-invoke.yml
examples/workflows/issue-triage/gemini-scheduled-triage.yml
examples/workflows/issue-triage/gemini-triage.yml
examples/workflows/pr-review/gemini-review.yml

The prompts in the workflows are updated to directly embed environment variables using `${{ env.VAR }}` syntax.
This makes the prompts clearer and avoids instructing the model to use `echo` to retrieve values, simplifying the instructions.
This should also improve quality of response.
cc @anj-s

refactor(workflows): improve prompts to use env vars directly
